![imagen](./img/python.jpg)

# Functional Programming
### Author: David Miró Asensi

In programming there are different paradigms. As we saw in previous notebooks, **Python is an object-oriented programming language**. However, it is quite versatile and **supports** other paradigms, such as **functional programming**. In this notebook you'll see the usefulness of this paradigm and how to use it in Python.

1. [Functional programming](#1.-Functional-programming)
2. [Lambda function](#2.-Lambda-function)
3. [Map](#3.-Map)
4. [Reduce](#4.-Reduce)
5. [Filter](#5.-Filter)
6. [Timeit](#6.-Timeit)
7. [Functional programming in Pandas](#7.-Functional-programming-in-Pandas)
8. [Summary](#8.-Summary)

## 1. Functional programming
Depending on the problem we want to solve, we will choose one programming paradigm or another. Let's see the difference between an object-oriented language and a functional one:

* **Object-Oriented Programming (OOP)**: this is the case of Python. In this paradigm we encapsulate program elements into objects, which have a type, **a state**, attributes and behaviors. Object-oriented languages include Java, Python, JavaScript, Ruby, among others.

* **Functional Programming**: The program is divided into a set of functions. Therefore, it is a continuous input/output flow: functions receive an *input*, perform operations, and return an *output*. Functional languages can offer good performance but are sometimes harder to develop because recursion is commonly used. Popular functional languages include [Clojure](https://clojure.org) and [Scala](https://www.scala-lang.org).

So, what is Python? Is it object-oriented...? Is it functional? **Python is object-oriented, but it also includes certain built-in features of functional programming**, such as `map` or `filter`, which give us alternative ways to solve problems and can improve performance.

As you can see, Python lets you mix object-oriented features with other paradigms like functional programming.

How can we iterate over a list and compute the sum of its elements?

In [42]:
lista = [1,2,3,4,5]

suma = 0
for i in lista:
    suma += i
suma

15

Aside from Python's built-in `sum()` function, we also have the option of using recursion, where we avoid loops and perform operations via functions only.

In [43]:
def suma_fun(lista):
    if len(lista) == 0:
        return 0
    return lista[0] + suma_fun(lista[1:])

In [44]:
lista = [1,2,3]
suma_fun(lista)

6

The main difference lies in **state**. In the `for` loop example the program's state changes due to variables like `suma` and `i`. In the recursive example there are no changing states: functions call other functions, receive an *input* and return an *output*. We'll explore this further in the notebook.

## 2. Lambda function
Recall the syntax to create a function:
```Python
def function_name(arguments):
    function body
    return output
```
A function has a name, parameters, operations inside and an output. Here we present a quicker way to create simple functions using the `lambda` expression. Lambdas let you create single-expression anonymous functions.

Lambda functions **are anonymous**; they have no name and simply evaluate the expression you declare.

Syntax:
```Python
lambda arguments: expression
```

Let's see an example

In [45]:
# Declare function
def suma(x,y):
    return x + y

# Assign to a variable
suma_var = suma

# Check type
print(type(suma_var))

# Use the function
suma_var(5, 7)

<class 'function'>

12

As you can see, functions are objects that can be assigned to variables. Now let's translate this into a `lambda` function.

In [46]:
lambda x,y: x + y

In [47]:
# If we assign it to a variable
suma_lambda = lambda x,y: x + y

suma_lambda(5,7)

12

Lambda functions are usually used as arguments to higher-order functions — functions that accept other functions as parameters — such as `map`, `reduce` or `filter`.

Lambdas can also make code more readable. Here's an example working with coordinates.

In [48]:
estaciones = ((40.4440297, -3.6956047), (40.4585318, -3.684715))

inicio = lambda x: x[0]
fin = lambda x: x[1]

print(inicio(estaciones))
print(fin(estaciones))

(40.4440297, -3.6956047)
(40.4585318, -3.684715)

In [49]:
lat = lambda x: x[0]
lon = lambda x: x[1]

print(lat(inicio(estaciones)))
print(lon(inicio(estaciones)))

40.4440297
-3.6956047

![exercise](./img/ejercicio.png)

### Working with lambda

1. Create a lambda function with three arguments that multiplies them.
2. Create another lambda with a single argument that computes its square root.

## 3. Map
`map` is a built-in function that takes two arguments: a function and an iterable (list, tuple, string, etc.). **It applies the function to each element of the iterable**. It maps every value of the iterable through the function and returns a new iterable with the results.

Syntax:
```Python
map(function, iterable)
```

`map` is a way to replace loop functionality. It is useful when you want to apply an operation to every element of a list.

In [50]:
my_list = [1,5,4,6,11]

# my_list + 2 is not valid for lists

new_list = map(lambda x: x + 2, my_list)

print(list(new_list))

[3, 7, 6, 8, 13]

Note that `map` returns a map object, which is an iterable that can be converted to a list. We used a simple `lambda` here, but you can pass any function. Here's another example with different operations.

In [51]:
my_tuple = (True, False, True, True)

my_tuple = map(lambda x: not x, my_tuple)

print(list(my_tuple))

[False, True, False, False]

`map` works with any iterable, so you can also apply it to strings.

In [52]:
my_tuple = ("AAA", "BBB", "CCC")

my_tuple = map(lambda x: "W-" + x, my_tuple)

print(tuple(my_tuple))

('W-AAA', 'W-BBB', 'W-CCC')

You can even separate the `lambda` function and reuse it elsewhere.

In [53]:
my_list = ("AAA", "BBB", "CCC")

my_fun = lambda x: "W-" + x

new_list = map(my_fun, my_list)

print(tuple(new_list))

('W-AAA', 'W-BBB', 'W-CCC')

**You can also pass your own functions.** Imagine the versatility: inside the function you can perform any calculation and it will be applied to each element of the iterable.

In [54]:
my_list = ("AAA", "BBB", "CCC")

def aniade_w(x):
    return "W-" + x

new_list = map(aniade_w, my_list)

print(tuple(new_list))

('W-AAA', 'W-BBB', 'W-CCC')

`map` also works with functions that accept multiple arguments: simply pass additional iterables to `map`. If the iterables have different lengths, `map` stops at the shortest one.

In [55]:
circle_areas = [3.56773, 5.57668, 4.00914, 56.24241, 9.01344, 32.00013]

decimales = range(1,7)
print(list(decimales))

# round(decimal_number, number_of_decimals)
result = map(round, circle_areas, decimales)

print(list(result))

[1, 2, 3, 4, 5, 6]
[3.6, 5.58, 4.009, 56.2424, 9.01344, 32.00013]

![exercise](./img/ejercicio.png)

### Working with map

1. Add "W-" to all keys of the dictionary.
2. Convert all elements of the tuple to integers.

In [56]:
my_dict = {'a':1,'b':2,'c':3}

new_dict = map(lambda x: "W-" + x, my_dict.keys())
print(list(new_dict))

['W-a', 'W-b', 'W-c']

In [57]:
def entero(x):
    return int(x)

In [58]:
int('2')

2

In [59]:
my_tuple = ('1','12','7')

new_tuple = map(int, my_tuple)

# print(tuple(new_tuple))

In [60]:
my_var= tuple(new_tuple)
my_var

(1, 12, 7)

## 4. Reduce
`reduce` is not a built-in but is included in the `functools` package. Its name hints at what it does: **it reduces/aggregates data**. Syntax:

```Python
reduce(function, iterable[, initial])
```

Like `map`, `reduce` takes a function and an iterable. The function passed to `reduce` receives two arguments (the first two elements of the iterable), and there is an optional third `initializer` argument to start the operation. While `map` transforms each element, **`reduce` aggregates all elements into a single value**.

In [61]:
from functools import reduce

lista = [1,3,5,6,2]

resultado = reduce(lambda x,y: x+y, lista)

print(resultado)

17

In [62]:
# (1+3) = 4 (4 + 5) = 9 (9+6) = 15 (15+2) = 17
# [1,3,5,6,2]
# [4,5,6,2]
# [9,6,2]
# [15,2]
# [17]

In [63]:
lista

[1, 3, 5, 6, 2]

Think of `reduce` like a recursive function: the inner function takes two arguments (the first two elements), then the result is combined with the third element using the same operation, and so on until the iterable is exhausted.

In [64]:
lista = [1,3,5,6,2]

resultado = reduce(lambda x,y: x+y, lista, 100)

print(resultado)

117

`reduce` accepts an optional third argument called `initializer`. By default it's `None`; if provided, the reduction starts with that value (as if it were the first element).

In [65]:
lista_strings = ["Hola ", " me", " llamo", " Ralph"]

resultado = reduce(lambda x,y: x+y, lista_strings)

print(resultado)

Hola  me llamo Ralph

![exercise](./img/ejercicio.png)

### Working with reduce

Use `reduce` to compute the product of all elements in the following tuple.

In [66]:
mi_tupla = (2,7,3,4,6)

In [67]:
resultado = reduce(lambda x,y: x*y, mi_tupla)
print(resultado)

1008

## 5. Filter
With this built-in function you can **filter elements from an iterable**. Syntax:

```Python
filter(function, iterable)
```

`filter` is similar to `map` but the function must return a boolean (`True`/`False`) — a mask — and only elements with `True` are kept. Unlike `map`, `filter` only uses a single iterable. You can pass lambdas or your own functions, but ensure the output is `True` or `False`.

Example:

In [68]:
lista = [ 1 , 3, 5, 6, 2]

filtrado = filter(lambda x: x >= 5, lista)

print(list(filtrado))

[5, 6]

Or implementing your own function:

In [69]:
lista = [ 1 , 3, 5, 6, 2]

def mas_cinco(x):
    if x >= 5:
        return True
    
    return False

filtrado = filter(mas_cinco, lista)

print(list(filtrado))

[5, 6]

As you can see, these are faster and more elegant ways to apply operations on collections.

![exercise](./img/ejercicio.png)

### Working with filter

Use `filter` to keep only the floats from the following tuple.

In [70]:
my_tuple = (1, 4., 10., 25)

In [71]:
def filter_floats(x):
    if type(x) == float:
        return True
    else:
        return False

filtrado = filter(filter_floats, my_tuple)
print(tuple(filtrado))

(4.0, 10.0)

In [72]:
filtrado = filter(lambda x: isinstance(x, float), my_tuple)
print(tuple(filtrado))

(4.0, 10.0)

## 6. Timeit
For the bootcamp, and generally when doing descriptive data analysis, runtime may not be critical. Imagine you created a heavy classifier that takes 0.5 seconds per transaction. If a user has 1000 transactions, the total time becomes 250 seconds (~4 minutes). Functional programming techniques can greatly improve performance because they avoid certain types of iteration.

Therefore, **when working with large datasets, consider using functions like `map`, `reduce`, and `filter` because they can yield significant performance improvements.**

In [73]:
num_elementos = 100000

lista = list(range(num_elementos))

In [74]:
%%timeit

lista_output = []
for i in lista:
    lista_output.append(i + 5)

8.48 ms ± 662 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [75]:
%%timeit

lista_output = map(lambda x: x + 5, lista)

260 ns ± 28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

As you can see, we can go from milliseconds to faster operations.

## 7. Functional programming in Pandas
Functional programming is useful when applying operations to every element of a column. In pandas we use the `apply` method.

Suppose we have a DataFrame of temperatures:

In [76]:
import pandas as pd

weather = pd.DataFrame({"temperatura": [20, 15, 34, 4, 1, 25, 21, 29, 40]})
weather

   temperatura
0           20
1           15
2           34
3            4
4            1
5           25
6           21
7           29
8           40

If we want to compute a new variable that indicates whether it's summer or winter, we can apply a custom function via `apply`. First we define the function.

In [77]:
def season(temp):
    if temp < 5:
        return "Winter"
    elif temp > 30:
        return "Summer"
    else:
        return "Other"
    
weather["season"] = weather["temperatura"].apply(season)
weather.head()

   temperatura  season
0           20   Other
1           15   Other
2           34  Summer
3            4  Winter
4            1  Winter

You can also use a lambda function.

In [78]:
weather["more_temperature"] = weather["temperatura"].apply(lambda x: x + 5)
weather.head()

   temperatura  season  more_temperature
0           20   Other                25
1           15   Other                20
2           34  Summer                39
3            4  Winter                 9
4            1  Winter                 6

In [79]:
weather["season_upper"] = weather["season"].apply(str.upper)
weather.head()

   temperatura  season  more_temperature season_upper
0           20   Other                25        OTHER
1           15   Other                20        OTHER
2           34  Summer                39       SUMMER
3            4  Winter                 9       WINTER
4            1  Winter                 6       WINTER

In [80]:
# (Degrees °C × 9 / 5) + 32 = F

weather["temperatura_F"] = weather["temperatura"].apply(lambda x: (x *9/5)+32)
weather

   temperatura  season  more_temperature season_upper  temperatura_F
0           20   Other                25        OTHER           68.0
1           15   Other                20        OTHER           59.0
2           34  Summer                39       SUMMER           93.2
3            4  Winter                 9       WINTER           39.2
4            1  Winter                 6       WINTER           33.8
5           25   Other                30        OTHER           77.0
6           21   Other                26        OTHER           69.8
7           29   Other                34        OTHER           84.2
8           40  Summer                45       SUMMER          104.0

In [81]:
import numpy as np

weather['Business'] = np.where(weather['temperatura']>=20, True, False)
weather.head()

   temperatura  season  more_temperature season_upper  temperatura_F  Business
0           20   Other                25        OTHER           68.0      True
1           15   Other                20        OTHER           59.0     False
2           34  Summer                39       SUMMER           93.2      True
3            4  Winter                 9       WINTER           39.2     False
4            1  Winter                 6       WINTER           33.8     False

## 8. Summary
As you have seen in this notebook (and in the recursion notebook), this style of programming is different: we think in terms of `input`/`output` rather than mutable state. The good thing about **Python is that it combines object-oriented programming with functional programming**, giving it great power.

In [82]:
# Lambda functions
suma_lambda = lambda x, y: x + y
print(suma_lambda(5, 7))


# Map function
my_list = [1, 5, 4, 6, 8, 11, 3, 12]
new_list = map(lambda x: x + 2 , my_list)
print(list(new_list))


# Reduce
from functools import reduce
lista = [ 1 , 3, 5, 6, 2]
print(reduce(lambda a,b : a+b, lista)) 


# Filter
lista = [ 1 , 3, 5, 6, 2]
filtrado = filter(lambda x: x >= 5, lista)
print(list(filtrado))

12
[3, 7, 6, 8, 10, 13, 5, 14]
17
[5, 6]