##  COBEE DATA CHALLENGE

In [1]:
import pandas as pd
import numpy as np

In [5]:
df_users = pd.read_excel('data_challenge_tables.xlsx', index_col = 0)

In [9]:
df_users

              name     surname  age     sex  company_id
user_id
1             John       Smith   34    Male           4
2          Marilyn        Russ   23  Female           3
3           Joseph   Malkovich   54    Male           6
4            Karen     Whitney   65  Female           5
5           Lauren       Green   23  Female          10
6            Linda     Houston   44  Female           1
7         Theodore       Light   67    Male           1
8          Melinda        Rock   12  Female           9
9           Nathan       Rogan   21    Male           8
10         Richard        Knox   34    Male           8
11          Arthur   McManaman   54    Male           8
12             Ken      Forest   26    Male           3
13            Shia        Gump   35  Female          10
14            Skye    Lurniman   33  Female           4
15          Sophia       Locke   20  Female          10
16          Jordan     Jameson   25    Male           3
17             Max    Kazowsky   18    Male           3
18        Courtney      Miller   57  Female           1
19          Luther       James   29    Male           9
20          Trebor    Buchanan   43    Male           5
21           James        Gale   27    Male           7
22         Timothy    Peterson   31    Male           1
23        Kimberly       Nixon   35  Female           7
24           Laura      Bright   38  Female           9
25       Elisabeth        Roly   21  Female          10
26          Martin     Bindack   30    Male           9
27         William      Meadow   37    Male           3
28         Michael       Bates   42    Male           8
29           Craig      Gibson   25    Male          10
30            Tony    Montello   33    Male          10
31          London     Johnson   45  Female           3
32           April   Riverside   22  Female           2
33          Andrew        Reis   29    Male          10
34           Sarah      Lumber   30  Female           4
35         Theresa      Cullen   46  Female           1
36          Claire  Timberland   34  Female           4
37           Julie       Brown   31  Female          10
38          Thomas         May   27    Male           8
39         Anthony         Red   29    Male           3
40           Jacob   Greenland   33    Male           5
41          Laurie       Fitch   40  Female           3
42            Mary      Dawson   22  Female           4
43            Jane  Richardson   34  Female           2
44           Alice      Knight   52  Female           9
45         Beverly        Dunn   48  Female           8
46         Lorenzo   Vinatello   29    Male           8
47            Gary       White   34    Male           9
48            Rita      Moreno   38  Female           2
49           Mandy       River   24  Female          10
50          Alfred      Dallas   29    Male           2

In [10]:
df_benefits = pd.read_excel('data_challenge-benefits.xlsx', index_col=0)

In [200]:
df_benefits

         benefit_name  user_id
_id
1    Health-Insurance       35
2           Transport       22
3                Meal       28
4                Meal       49
5             Nursery       26
..                ...      ...
96               Meal       20
97               Meal        9
98          Transport       19
99               Meal       38
100              Meal       34

[100 rows x 2 columns]

In [14]:
df_companies = pd.read_excel('data_challenge_compañías.xlsx', index_col=0)

In [15]:
df_companies

               company_name           city  monthly_price_per_user
company_id
1                Futureland      San Diego                      20
2           Cosmetic Powers    Los Angeles                      25
3                   Riverfy      San Diego                      15
4                   Loomtic  San Francisco                      30
5                  Kuantyko  San Francisco                      30
6               Blue Portal  San Francisco                      30
7                Trainclock    Los Angeles                      30
8             Angry Monkeys  San Francisco                      20
9                   LandApp  San Francisco                      30
10                MyLastCar    Los Angeles                      10

In [16]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [21]:
df_display = display('df_users', 'df_benefits', "pd.merge(df_users, df_benefits, on='user_id')")

In [22]:
df_display

df_users
              name     surname  age     sex  company_id
user_id
1             John       Smith   34    Male           4
2          Marilyn        Russ   23  Female           3
3           Joseph   Malkovich   54    Male           6
4            Karen     Whitney   65  Female           5
5           Lauren       Green   23  Female          10
6            Linda     Houston   44  Female           1
7         Theodore       Light   67    Male           1
8          Melinda        Rock   12  Female           9
9           Nathan       Rogan   21    Male           8
10         Richard        Knox   34    Male           8
11          Arthur   McManaman   54    Male           8
12             Ken      Forest   26    Male           3
13            Shia        Gump   35  Female          10
14            Skye    Lurniman   33  Female           4
15          Sophia       Locke   20  Female          10
16          Jordan     Jameson   25    Male           3
17             Max    Kazowsky   18    Male           3
18        Courtney      Miller   57  Female           1
19          Luther       James   29    Male           9
20          Trebor    Buchanan   43    Male           5
21           James        Gale   27    Male           7
22         Timothy    Peterson   31    Male           1
23        Kimberly       Nixon   35  Female           7
24           Laura      Bright   38  Female           9
25       Elisabeth        Roly   21  Female          10
26          Martin     Bindack   30    Male           9
27         William      Meadow   37    Male           3
28         Michael       Bates   42    Male           8
29           Craig      Gibson   25    Male          10
30            Tony    Montello   33    Male          10
31          London     Johnson   45  Female           3
32           April   Riverside   22  Female           2
33          Andrew        Reis   29    Male          10
34           Sarah      Lumber   30  Female           4
35         Theresa      Cullen   46  Female           1
36          Claire  Timberland   34  Female           4
37           Julie       Brown   31  Female          10
38          Thomas         May   27    Male           8
39         Anthony         Red   29    Male           3
40           Jacob   Greenland   33    Male           5
41          Laurie       Fitch   40  Female           3
42            Mary      Dawson   22  Female           4
43            Jane  Richardson   34  Female           2
44           Alice      Knight   52  Female           9
45         Beverly        Dunn   48  Female           8
46         Lorenzo   Vinatello   29    Male           8
47            Gary       White   34    Male           9
48            Rita      Moreno   38  Female           2
49           Mandy       River   24  Female          10
50          Alfred      Dallas   29    Male           2

df_benefits
         benefit_name  user_id
_id
1    Health-Insurance       35
2           Transport       22
3                Meal       28
4                Meal       49
5             Nursery       26
..                ...      ...
96               Meal       20
97               Meal        9
98          Transport       19
99               Meal       38
100              Meal       34

[100 rows x 2 columns]

pd.merge(df_users, df_benefits, on='user_id')
    user_id     name    surname  age     sex  company_id      benefit_name
0         1     John      Smith   34    Male           4         Transport
1         1     John      Smith   34    Male           4              Meal
2         2  Marilyn       Russ   23  Female           3              Meal
3         2  Marilyn       Russ   23  Female           3         Transport
4         3   Joseph  Malkovich   54    Male           6              Meal
..      ...      ...        ...  ...     ...         ...               ...
95       47     Gary      White   34    Male           9  Health-Insurance
96       48     Rita     Moreno   38  Female           2         Education
97       48     Rita     Moreno   38  Female           2              Meal
98       49    Mandy      River   24  Female          10              Meal
99       50   Alfred     Dallas   29    Male           2              Meal

[100 rows x 7 columns]

In [24]:
df3 = pd.merge(df_users, df_benefits, on='user_id')

In [25]:
df3

    user_id     name    surname  age     sex  company_id      benefit_name
0         1     John      Smith   34    Male           4         Transport
1         1     John      Smith   34    Male           4              Meal
2         2  Marilyn       Russ   23  Female           3              Meal
3         2  Marilyn       Russ   23  Female           3         Transport
4         3   Joseph  Malkovich   54    Male           6              Meal
..      ...      ...        ...  ...     ...         ...               ...
95       47     Gary      White   34    Male           9  Health-Insurance
96       48     Rita     Moreno   38  Female           2         Education
97       48     Rita     Moreno   38  Female           2              Meal
98       49    Mandy      River   24  Female          10              Meal
99       50   Alfred     Dallas   29    Male           2              Meal

[100 rows x 7 columns]

In [26]:
df_cobee = pd.merge(df3, df_companies, on='company_id')

In [27]:
df_cobee

,user_id,name,surname,age,sex,company_id,benefit_name,company_name,city,monthly_price_per_user
0,1,John,Smith,34,Male,4,Transport,Loomtic,San Francisco,30
1,1,John,Smith,34,Male,4,Meal,Loomtic,San Francisco,30
2,14,Skye,Lurniman,33,Female,4,Health-Insurance,Loomtic,San Francisco,30
3,34,Sarah,Lumber,30,Female,4,Meal,Loomtic,San Francisco,30
4,36,Claire,Timberland,34,Female,4,Transport,Loomtic,San Francisco,30
...,...,...,...,...,...,...,...,...,...,...
95,43,Jane,Richardson,34,Female,2,Education,Cosmetic Powers,Los Angeles,25
96,43,Jane,Richardson,34,Female,2,Meal,Cosmetic Powers,Los Angeles,25
97,48,Rita,Moreno,38,Female,2,Education,Cosmetic Powers,Los Angeles,25
98,48,Rita,Moreno,38,Female,2,Meal,Cosmetic Powers,Los Angeles,25
99,50,Alfred,Dallas,29,Male,2,Meal,Cosmetic Powers,Los Angeles,25

In [28]:
df_cobee.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 100 non-null    int64
 1   name                    100 non-null    object
 2   surname                 100 non-null    object
 3   age                     100 non-null    int64
 4   sex                     100 non-null    object
 5   company_id              100 non-null    int64
 6   benefit_name            100 non-null    object
 7   company_name            100 non-null    object
 8   city                    100 non-null    object
 9   monthly_price_per_user  100 non-null    int64
dtypes: int64(4), object(6)
memory usage: 8.6+ KB

In [29]:
df_cobee.describe()

         user_id        age  company_id  monthly_price_per_user
count  100.00000  100.00000  100.000000              100.000000
mean    25.76000   33.98000    5.970000               21.750000
std     13.88635   10.84508    3.233208                7.633492
min      1.00000   12.00000    1.000000               10.000000
25%     14.75000   27.00000    3.000000               15.000000
50%     26.00000   33.00000    7.000000               20.000000
75%     37.25000   38.00000    9.000000               30.000000
max     50.00000   67.00000   10.000000               30.000000

In [30]:
df_cobee['monthly_price_per_user'].max()

30

In [41]:
df_cobee.loc[df_cobee.monthly_price_per_user.max(), ['company_name']]

company_name    Kuantyko
Name: 30, dtype: object

In [42]:
df_cobee.loc[df_cobee.monthly_price_per_user >= 30, ['company_name']]

   company_name
0       Loomtic
1       Loomtic
2       Loomtic
3       Loomtic
4       Loomtic
5       Loomtic
6       Loomtic
7       Loomtic
8       Loomtic
9       Loomtic
25  Blue Portal
26  Blue Portal
27     Kuantyko
28     Kuantyko
29     Kuantyko
30     Kuantyko
58      LandApp
59      LandApp
60      LandApp
61      LandApp
62      LandApp
63      LandApp
64      LandApp
65      LandApp
66      LandApp
67      LandApp
68      LandApp
69      LandApp
70      LandApp
71      LandApp
72      LandApp
73      LandApp
74      LandApp
87   Trainclock
88   Trainclock
89   Trainclock
90   Trainclock
91   Trainclock

In [48]:
df_cobee[['benefit_name']]

        benefit_name
0          Transport
1               Meal
2   Health-Insurance
3               Meal
4          Transport
..               ...
95         Education
96              Meal
97         Education
98              Meal
99              Meal

[100 rows x 1 columns]

In [137]:
df_cobee['benefit_name'].unique()

array(['Transport', 'Meal', 'Health-Insurance', 'Nursery', 'Education'],
      dtype=object)

In [62]:
insurance = df_cobee[df_cobee['benefit_name'] == 'Health-Insurance']
insurance

,user_id,name,surname,age,sex,company_id,benefit_name,company_name,city,monthly_price_per_user
2,14,Skye,Lurniman,33,Female,4,Health-Insurance,Loomtic,San Francisco,30
9,42,Mary,Dawson,22,Female,4,Health-Insurance,Loomtic,San Francisco,30
16,17,Max,Kazowsky,18,Male,3,Health-Insurance,Riverfy,San Diego,15
19,31,London,Johnson,45,Female,3,Health-Insurance,Riverfy,San Diego,15
24,41,Laurie,Fitch,40,Female,3,Health-Insurance,Riverfy,San Diego,15
27,4,Karen,Whitney,65,Female,5,Health-Insurance,Kuantyko,San Francisco,30
46,37,Julie,Brown,31,Female,10,Health-Insurance,MyLastCar,Los Angeles,10
51,7,Theodore,Light,67,Male,1,Health-Insurance,Futureland,San Diego,20
57,35,Theresa,Cullen,46,Female,1,Health-Insurance,Futureland,San Diego,20
67,26,Martin,Bindack,30,Male,9,Health-Insurance,LandApp,San Francisco,30
74,47,Gary,White,34,Male,9,Health-Insurance,LandApp,San Francisco,30
89,23,Kimberly,Nixon,35,Female,7,Health-Insurance,Trainclock,Los Angeles,30

In [ ]:
# La media de edad de todas las compañías es de 33.98

In [63]:
df_cobee['age'].mean()

33.98

In [ ]:
# La media de edad agrupada por cada una de las compañías es de:

In [ ]:
df_cobee = pd.merge(df3, df_companies, on='company_id')

In [188]:
df_edad = pd.merge(df_users, df_companies, on ='company_id' )

In [ ]:
df_beneficios = pd.merge(df_edad, df_benefits, on = 'user_id')

In [199]:
df_edad

,name,surname,age,sex,company_id,company_name,city,monthly_price_per_user
0,John,Smith,34,Male,4,Loomtic,San Francisco,30
1,Skye,Lurniman,33,Female,4,Loomtic,San Francisco,30
2,Sarah,Lumber,30,Female,4,Loomtic,San Francisco,30
3,Claire,Timberland,34,Female,4,Loomtic,San Francisco,30
4,Mary,Dawson,22,Female,4,Loomtic,San Francisco,30
5,Marilyn,Russ,23,Female,3,Riverfy,San Diego,15
6,Ken,Forest,26,Male,3,Riverfy,San Diego,15
7,Jordan,Jameson,25,Male,3,Riverfy,San Diego,15
8,Max,Kazowsky,18,Male,3,Riverfy,San Diego,15
9,William,Meadow,37,Male,3,Riverfy,San Diego,15
10,London,Johnson,45,Female,3,Riverfy,San Diego,15
11,Anthony,Red,29,Male,3,Riverfy,San Diego,15
12,Laurie,Fitch,40,Female,3,Riverfy,San Diego,15
13,Joseph,Malkovich,54,Male,6,Blue Portal,San Francisco,30
14,Karen,Whitney,65,Female,5,Kuantyko,San Francisco,30
15,Trebor,Buchanan,43,Male,5,Kuantyko,San Francisco,30
16,Jacob,Greenland,33,Male,5,Kuantyko,San Francisco,30
17,Lauren,Green,23,Female,10,MyLastCar,Los Angeles,10
18,Shia,Gump,35,Female,10,MyLastCar,Los Angeles,10
19,Sophia,Locke,20,Female,10,MyLastCar,Los Angeles,10
20,Elisabeth,Roly,21,Female,10,MyLastCar,Los Angeles,10
21,Craig,Gibson,25,Male,10,MyLastCar,Los Angeles,10
22,Tony,Montello,33,Male,10,MyLastCar,Los Angeles,10
23,Andrew,Reis,29,Male,10,MyLastCar,Los Angeles,10
24,Julie,Brown,31,Female,10,MyLastCar,Los Angeles,10
25,Mandy,River,24,Female,10,MyLastCar,Los Angeles,10
26,Linda,Houston,44,Female,1,Futureland,San Diego,20
27,Theodore,Light,67,Male,1,Futureland,San Diego,20
28,Courtney,Miller,57,Female,1,Futureland,San Diego,20
29,Timothy,Peterson,31,Male,1,Futureland,San Diego,20
30,Theresa,Cullen,46,Female,1,Futureland,San Diego,20
31,Melinda,Rock,12,Female,9,LandApp,San Francisco,30
32,Luther,James,29,Male,9,LandApp,San Francisco,30
33,Laura,Bright,38,Female,9,LandApp,San Francisco,30
34,Martin,Bindack,30,Male,9,LandApp,San Francisco,30
35,Alice,Knight,52,Female,9,LandApp,San Francisco,30
36,Gary,White,34,Male,9,LandApp,San Francisco,30
37,Nathan,Rogan,21,Male,8,Angry Monkeys,San Francisco,20
38,Richard,Knox,34,Male,8,Angry Monkeys,San Francisco,20
39,Arthur,McManaman,54,Male,8,Angry Monkeys,San Francisco,20
40,Michael,Bates,42,Male,8,Angry Monkeys,San Francisco,20
41,Thomas,May,27,Male,8,Angry Monkeys,San Francisco,20
42,Beverly,Dunn,48,Female,8,Angry Monkeys,San Francisco,20
43,Lorenzo,Vinatello,29,Male,8,Angry Monkeys,San Francisco,20
44,James,Gale,27,Male,7,Trainclock,Los Angeles,30
45,Kimberly,Nixon,35,Female,7,Trainclock,Los Angeles,30
46,April,Riverside,22,Female,2,Cosmetic Powers,Los Angeles,25
47,Jane,Richardson,34,Female,2,Cosmetic Powers,Los Angeles,25
48,Rita,Moreno,38,Female,2,Cosmetic Powers,Los Angeles,25
49,Alfred,Dallas,29,Male,2,Cosmetic Powers,Los Angeles,25

In [ ]:
df_edad.groupby(['company_name'])['age'].mean()

In [206]:
df_edad.groupby(['company_name'])['monthly_price_per_user'].sum()

company_name
Angry Monkeys      140
Blue Portal         30
Cosmetic Powers    100
Futureland         100
Kuantyko            90
LandApp            180
Loomtic            150
MyLastCar           90
Riverfy            120
Trainclock          60
Name: monthly_price_per_user, dtype: int64

In [205]:
df_edad['name'].value_counts()

John         1
Nathan       1
Theodore     1
Courtney     1
Timothy      1
Theresa      1
Melinda      1
Luther       1
Laura        1
Martin       1
Alice        1
Gary         1
Richard      1
Skye         1
Arthur       1
Michael      1
Thomas       1
Beverly      1
Lorenzo      1
James        1
Kimberly     1
April        1
Jane         1
Rita         1
Linda        1
Mandy        1
Julie        1
Andrew       1
Sarah        1
Claire       1
Mary         1
Marilyn      1
Ken          1
Jordan       1
Max          1
William      1
London       1
Anthony      1
Laurie       1
Joseph       1
Karen        1
Trebor       1
Jacob        1
Lauren       1
Shia         1
Sophia       1
Elisabeth    1
Craig        1
Tony         1
Alfred       1
Name: name, dtype: int64

In [181]:
df_edad.groupby(['company_name'])['age'].mean()

company_name
Angry Monkeys      36.428571
Blue Portal        54.000000
Cosmetic Powers    30.750000
Futureland         49.000000
Kuantyko           47.000000
LandApp            32.500000
Loomtic            30.600000
MyLastCar          26.777778
Riverfy            30.375000
Trainclock         31.000000
Name: age, dtype: float64

In [182]:
df_edad['age'].mean()

34.24

In [184]:
df_edad.groupby(['city'])['monthly_price_per_user'].sum()

city
Los Angeles      250
San Diego        220
San Francisco    590
Name: monthly_price_per_user, dtype: int64

In [191]:
education = df_cobee[df_cobee['benefit_name'] == 'Education']
education

,user_id,name,surname,age,sex,company_id,benefit_name,company_name,city,monthly_price_per_user
13,16,Jordan,Jameson,25,Male,3,Education,Riverfy,San Diego,15
21,39,Anthony,Red,29,Male,3,Education,Riverfy,San Diego,15
48,6,Linda,Houston,44,Female,1,Education,Futureland,San Diego,20
60,19,Luther,James,29,Male,9,Education,LandApp,San Francisco,30
62,24,Laura,Bright,38,Female,9,Education,LandApp,San Francisco,30
69,26,Martin,Bindack,30,Male,9,Education,LandApp,San Francisco,30
94,32,April,Riverside,22,Female,2,Education,Cosmetic Powers,Los Angeles,25
95,43,Jane,Richardson,34,Female,2,Education,Cosmetic Powers,Los Angeles,25
97,48,Rita,Moreno,38,Female,2,Education,Cosmetic Powers,Los Angeles,25

In [193]:
benefits_edu = pd.Series(education['benefit_name'])
sex = pd.Series(education['sex'])
units = pd.Series(education['user_id'])
benefits_sex = pd.DataFrame({'Benefits of Education': benefits_edu, 'Sex': sex})

benefits_sex

   Benefits of Education     Sex
13             Education    Male
21             Education    Male
48             Education  Female
60             Education    Male
62             Education  Female
69             Education    Male
94             Education  Female
95             Education  Female
97             Education  Female

In [194]:
suma = benefits_sex.groupby('Sex').sum()
suma

                                Benefits of Education
Sex
Female  EducationEducationEducationEducationEducation
Male             EducationEducationEducationEducation

In [195]:
# Female

(5 * 100)/9

55.55555555555556

In [196]:
# Male

(4 * 100)/9

44.44444444444444

In [ ]:
df_edad

In [121]:
city = df_cobee[df_cobee['city'] == 'San Diego']
city

,user_id,name,surname,age,sex,company_id,benefit_name,company_name,city,monthly_price_per_user
10,2,Marilyn,Russ,23,Female,3,Meal,Riverfy,San Diego,15
11,2,Marilyn,Russ,23,Female,3,Transport,Riverfy,San Diego,15
12,12,Ken,Forest,26,Male,3,Meal,Riverfy,San Diego,15
13,16,Jordan,Jameson,25,Male,3,Education,Riverfy,San Diego,15
14,16,Jordan,Jameson,25,Male,3,Meal,Riverfy,San Diego,15
15,16,Jordan,Jameson,25,Male,3,Transport,Riverfy,San Diego,15
16,17,Max,Kazowsky,18,Male,3,Health-Insurance,Riverfy,San Diego,15
17,27,William,Meadow,37,Male,3,Meal,Riverfy,San Diego,15
18,31,London,Johnson,45,Female,3,Meal,Riverfy,San Diego,15
19,31,London,Johnson,45,Female,3,Health-Insurance,Riverfy,San Diego,15
20,39,Anthony,Red,29,Male,3,Meal,Riverfy,San Diego,15
21,39,Anthony,Red,29,Male,3,Education,Riverfy,San Diego,15
22,39,Anthony,Red,29,Male,3,Transport,Riverfy,San Diego,15
23,39,Anthony,Red,29,Male,3,Nursery,Riverfy,San Diego,15
24,41,Laurie,Fitch,40,Female,3,Health-Insurance,Riverfy,San Diego,15
48,6,Linda,Houston,44,Female,1,Education,Futureland,San Diego,20
49,6,Linda,Houston,44,Female,1,Transport,Futureland,San Diego,20
50,6,Linda,Houston,44,Female,1,Meal,Futureland,San Diego,20
51,7,Theodore,Light,67,Male,1,Health-Insurance,Futureland,San Diego,20
52,7,Theodore,Light,67,Male,1,Meal,Futureland,San Diego,20
53,18,Courtney,Miller,57,Female,1,Meal,Futureland,San Diego,20
54,18,Courtney,Miller,57,Female,1,Transport,Futureland,San Diego,20
55,22,Timothy,Peterson,31,Male,1,Transport,Futureland,San Diego,20
56,22,Timothy,Peterson,31,Male,1,Meal,Futureland,San Diego,20
57,35,Theresa,Cullen,46,Female,1,Health-Insurance,Futureland,San Diego,20

In [132]:
city.groupby('user_id').max()

,name,surname,age,sex,company_id,benefit_name,company_name,city,monthly_price_per_user
user_id,,,,,,,,,
2,Marilyn,Russ,23,Female,3,Transport,Riverfy,San Diego,15
6,Linda,Houston,44,Female,1,Transport,Futureland,San Diego,20
7,Theodore,Light,67,Male,1,Meal,Futureland,San Diego,20
12,Ken,Forest,26,Male,3,Meal,Riverfy,San Diego,15
16,Jordan,Jameson,25,Male,3,Transport,Riverfy,San Diego,15
17,Max,Kazowsky,18,Male,3,Health-Insurance,Riverfy,San Diego,15
18,Courtney,Miller,57,Female,1,Transport,Futureland,San Diego,20
22,Timothy,Peterson,31,Male,1,Transport,Futureland,San Diego,20
27,William,Meadow,37,Male,3,Meal,Riverfy,San Diego,15
31,London,Johnson,45,Female,3,Meal,Riverfy,San Diego,15
35,Theresa,Cullen,46,Female,1,Health-Insurance,Futureland,San Diego,20
39,Anthony,Red,29,Male,3,Transport,Riverfy,San Diego,15
41,Laurie,Fitch,40,Female,3,Health-Insurance,Riverfy,San Diego,15