In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('users_web.csv')
df

          Date  Users
0     1/1/2020     13
1     2/1/2020     17
2     3/1/2020     13
3     4/1/2020      4
4     5/1/2020     10
..         ...    ...
846  26/4/2022     63
847  27/4/2022     64
848  28/4/2022     46
849  29/4/2022     29
850  30/4/2022     21

[851 rows x 2 columns]

In [5]:
datos_nuevos = df[-15:]
datos_test = df[-30:-15]
datos_train = df[:-30]

In [ ]:
endpoint_bd = "Endpoint donde se añaden los nuevos registros a la bbdd"

In [6]:
datos_nuevos

          Date  Users
836  16/4/2022     33
837  17/4/2022     52
838  18/4/2022     56
839  19/4/2022     66
840  20/4/2022     59
841  21/4/2022     51
842  22/4/2022     48
843  23/4/2022     42
844  24/4/2022     36
845  25/4/2022     65
846  26/4/2022     63
847  27/4/2022     64
848  28/4/2022     46
849  29/4/2022     29
850  30/4/2022     21