# Ex3 - Getting and Knowing your Data



### Step 1. Import the necessary libraries

In [14]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [15]:
!pip freeze

aiobotocore @ file:///C:/miniconda3/conda-bld/aiobotocore_1760994335546/work
aiodns @ file:///C:/miniconda3/conda-bld/aiodns_1762185075564/work
aiohappyeyeballs @ file:///C:/b/abs_f806x82huz/croot/aiohappyeyeballs_1755769855628/work
aiohttp @ file:///C:/miniconda3/conda-bld/aiohttp_1762519774760/work
aioitertools @ file:///C:/b/abs_70vydn6fmg/croot/aioitertools_1754313763510/work
aiosignal @ file:///C:/b/abs_84ej696pud/croot/aiosignal_1755870823775/work
alabaster @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/alabaster_1729041938345/work
altair @ file:///C:/b/abs_0b1avjyzoc/croot/altair_1743016738596/work
anaconda-anon-usage @ file:///opt/miniconda3/conda-bld/anaconda-anon-usage_1764636648062/work
anaconda-auth @ file:///C:/miniconda3/conda-bld/anaconda-cloud-auth-split_1764891486360/work
anaconda-catalogs @ file:///C:/miniconda3/conda-bld/anaconda-catalogs_1764859031645/work
anaconda-cli-base @ file:///C:/miniconda3/conda-bld/anaconda-cli-base_1764888883727/work
anaconda-client @ file:///C:/miniconda3/conda-bld/anaconda-client_1763659439838/work
anaconda-navigator @ file:///C:/miniconda3/conda-bld/anaconda-navigator_1761578688358/work
anaconda-project @ file:///C:/b/abs_c3nd60wjs2/croot/anaconda-project_1746215311215/work
annotated-types @ file:///C:/miniconda3/conda-bld/annotated-types_1761745107361/work
anyio @ file:///C:/miniconda3/conda-bld/anyio_1758622433823/work
appdirs==1.4.4
archspec @ file:///home/task_175812491784513/conda-bld/archspec_1758124989039/work
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/miniconda3/conda-bld/argon2-cffi-bindings_1757925023673/work
arrow @ file:///C:/miniconda3/conda-bld/arrow_1761560549461/work
astroid @ file:///C:/miniconda3/conda-bld/astroid_1759355341836/work
astropy @ file:///C:/miniconda3/conda-bld/astropy_1762433878873/work
astropy-iers-data @ file:///C:/miniconda3/conda-bld/astropy-iers-data_1763019997878/work
asttokens @ file:///C:/b/abs_9662ywy9fp/croot/asttokens_1743630464377/work
async-lru @ file:///C:/miniconda3/conda-bld/async-lru_1761121577604/work
asyncssh @ file:///C:/miniconda3/conda-bld/asyncssh_1763120359147/work
atomicwrites==1.4.0
attrs @ file:///C:/miniconda3/conda-bld/attrs_1762356899359/work
Automat @ file:///C:/b/abs_e6j20ekmp5/croot/automat_1743532580167/work
autopep8 @ file:///croot/autopep8_1708962882016/work
babel @ file:///C:/miniconda3/conda-bld/babel_1764159345001/work
bcrypt @ file:///C:/miniconda3/conda-bld/bcrypt_1762875213278/work
beautifulsoup4 @ file:///C:/b/abs_95vq944bnw/croot/beautifulsoup4-split_1756453107890/work
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
black @ file:///C:/miniconda3/conda-bld/black_1760632469648/work
bleach @ file:///C:/miniconda3/conda-bld/bleach_1764153675285/work
blinker @ file:///C:/b/abs_b1i87khtob/croot/blinker_1737448732095/work
bokeh @ file:///C:/miniconda3/conda-bld/bokeh_1757102818337/work
boltons @ file:///C:/b/abs_e2_iokhxbp/croot/boltons_1751383740243/work
botocore @ file:///C:/miniconda3/conda-bld/botocore_1760965317697/work
Bottleneck @ file:///C:/miniconda3/conda-bld/bottleneck_1761938102004/work
brotlicffi @ file:///C:/miniconda3/conda-bld/brotlicffi_1762950508507/work
cachetools @ file:///C:/b/abs_fcvwpc5vh9/croot/cachetools_1738224687938/work
cattrs @ file:///C:/miniconda3/conda-bld/cattrs_1761729120648/work
certifi @ file:///C:/miniconda3/conda-bld/certifi_1763135348719/work/certifi
cffi @ file:///C:/miniconda3/conda-bld/cffi_1761832792955/work
chardet @ file:///C:/b/abs_3f08pnpj_d/croot/chardet_1755516293556/work
charset-normalizer @ file:///C:/miniconda3/conda-bld/charset-normalizer_1761744975868/work
click @ file:///C:/b/abs_bbg7qqz4dk/croot/click_1754477951021/work
cloudpickle @ file:///C:/b/abs_fdydcrc9_2/croot/cloudpickle_1751309451995/work
colorama @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/colorama_1729036581634/work
colorcet @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/colorcet_1729053366498/work
comm @ file:///C:/miniconda3/conda-bld/comm_1763119281973/work
conda @ file:///C:/miniconda3/conda-bld/conda_1764069071297/work/conda-src
conda-anaconda-telemetry @ file:///croot/conda-anaconda-telemetry_1755883788794/work
conda-anaconda-tos @ file:///C:/b/abs_c9yejtsx9g/croot/conda-anaconda-tos_1755123332641/work
conda-build @ file:///C:/miniconda3/conda-bld/conda-build_1764886947283/work
conda-content-trust @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/conda-content-trust_1729088072778/work
conda-libmamba-solver @ file:///C:/miniconda3/conda-bld/conda-libmamba-solver_1764245615235/work/src
conda-pack @ file:///C:/b/abs_7b5jwr84ex/croot/conda-pack_1752674284442/work
conda-package-handling @ file:///C:/miniconda3/conda-bld/conda-package-handling_1762366515145/work
conda-repo-cli @ file:///C:/b/abs_e2mlfkr6jb/croot/conda-repo-cli_1755793053578/work
conda_index @ file:///C:/miniconda3/conda-bld/conda-index_1761321711844/work
conda_package_streaming @ file:///C:/miniconda3/conda-bld/conda-package-streaming_1762361689679/work
constantly @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/constantly_1729053406505/work
contourpy @ file:///C:/miniconda3/conda-bld/contourpy_1763643940481/work
cookiecutter @ file:///C:/b/abs_6ak0be77em/croot/cookiecutter_1751313989831/work
cryptography @ file:///C:/miniconda3/conda-bld/cryptography-split_1761932023265/work
cssselect @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/cssselect_1729047831562/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
dask @ file:///C:/miniconda3/conda-bld/dask-core_1763019062292/work
datashader @ file:///C:/b/abs_0dvz2ks6tk/croot/datashader_1756382478739/work
debugpy @ file:///C:/miniconda3/conda-bld/debugpy_1762421658007/work
decorator @ file:///C:/miniconda3/conda-bld/decorator_1757341249916/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work
dill @ file:///C:/miniconda3/conda-bld/dill_1760096877594/work
distributed @ file:///C:/miniconda3/conda-bld/distributed_1763105975646/work
distro @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/distro_1729059153117/work
docstring-to-markdown @ file:///C:/miniconda3/conda-bld/docstring-to-markdown_1758626863507/work
docutils @ file:///C:/miniconda3/conda-bld/docutils_1761746640431/work
et_xmlfile @ file:///C:/b/abs_b0ifp_j3js/croot/et_xmlfile_1756462499666/work
evalidate @ file:///C:/b/abs_573nc1ymt6/croot/evalidate_1743606028415/work
executing @ file:///C:/miniconda3/conda-bld/executing_1757061255268/work
fastjsonschema @ file:///C:/miniconda3/conda-bld/python-fastjsonschema_1763718729498/work
filelock @ file:///C:/miniconda3/conda-bld/filelock_1762419942375/work
flake8 @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/flake8_1729054074515/work
Flask @ file:///C:/b/abs_28dbmjidmh/croot/flask_1756453142071/work
fonttools @ file:///C:/miniconda3/conda-bld/fonttools_1759754890124/work
frozendict @ file:///C:/miniconda3/conda-bld/frozendict_1761750728192/work
frozenlist @ file:///C:/miniconda3/conda-bld/frozenlist_1761062034652/work
fsspec @ file:///C:/miniconda3/conda-bld/fsspec_1762432453760/work
gitdb @ file:///C:/b/abs_1bkmriimss/croot/gitdb_1753362133190/work
GitPython @ file:///C:/miniconda3/conda-bld/gitpython_1761291338863/work
gmpy2 @ file:///C:/b/abs_d8ki0o0h97/croot/gmpy2_1738085498525/work
greenlet @ file:///C:/miniconda3/conda-bld/greenlet_1757405549674/work
h11 @ file:///C:/miniconda3/conda-bld/h11_1761931384726/work
h5py @ file:///C:/miniconda3/conda-bld/h5py_1763997403619/work
HeapDict @ file:///Users/ktietz/demo/mc3/conda-bld/heapdict_1630598515714/work
holoviews @ file:///C:/miniconda3/conda-bld/holoviews_1763365342364/work
html5lib @ file:///Users/ktietz/demo/mc3/conda-bld/html5lib_1629144453894/work
httpcore @ file:///C:/b/abs_25m7_xthp6/croot/httpcore_1748526065845/work
httpx @ file:///C:/miniconda3/conda-bld/httpx_1760447475275/work
hvplot @ file:///C:/miniconda3/conda-bld/hvplot_1756992721648/work
hyperlink @ file:///tmp/build/80754af9/hyperlink_1610130746837/work
idna @ file:///C:/miniconda3/conda-bld/idna_1761912043388/work
ImageIO @ file:///C:/miniconda3/conda-bld/imageio_1762954225001/work
imagesize @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/imagesize_1729042613392/work
imbalanced-learn @ file:///C:/b/abs_d1hr2znu7o/croot/imbalanced-learn_1756460314059/work
importlib_metadata @ file:///C:/miniconda3/conda-bld/importlib_metadata-suite_1763996638226/work
incremental @ file:///croot/incremental_1743512672142/work
inflection @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/inflection_1729054658204/work
iniconfig @ file:///C:/b/abs_70kaor_ccd/croot/iniconfig_1752653749904/work
intake @ file:///C:/b/abs_36v90t4ek6/croot/intake_1752749551025/work
intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work
ipykernel @ file:///C:/miniconda3/conda-bld/ipykernel_1762946092426/work
ipympl @ file:///C:/b/abs_2fdfe_fnms/croot/ipympl_1752060862279/work
ipython @ file:///C:/miniconda3/conda-bld/ipython_1762789322374/work
ipython_pygments_lexers @ file:///C:/b/abs_b66hj1lo19/croot/ipython_pygments_lexers_1744753262043/work
ipywidgets @ file:///C:/miniconda3/conda-bld/ipywidgets_1761560177683/work
isort @ file:///C:/miniconda3/conda-bld/isort_1760089000590/work
itemadapter @ file:///C:/b/abs_87vsk6a5ji/croot/itemadapter_1756732900203/work
itemloaders @ file:///C:/b/abs_f35dqz89dk/croot/itemloaders_1743513855167/work
itsdangerous @ file:///C:/Users/dev-admin/buildout/croot/itsdangerous_1732929022589/work
jaraco.classes @ file:///C:/b/abs_6erueoob1v/croot/jaraco.classes_1755516340851/work
jaraco.context @ file:///C:/Users/dev-admin/buildout/perseverance-python-buildout/croot/jaraco.context_1731721000658/work
jaraco.functools @ file:///C:/b/abs_a1jv6v_pzp/croot/jaraco.functools_1740408129620/work
jedi @ file:///C:/b/abs_3a2kbnlclc/croot/jedi_1733987412687/work
jellyfish @ file:///C:/miniconda3/conda-bld/jellyfish_1764243816637/work
Jinja2 @ file:///C:/b/abs_920kup4e6u/croot/jinja2_1741711580669/work
jmespath @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/jmespath_1729040936778/work
joblib @ file:///C:/miniconda3/conda-bld/joblib_1757926362684/work
json5 @ file:///C:/miniconda3/conda-bld/json5_1763718601351/work
jsonpatch @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/jsonpatch_1729054776004/work
jsonpointer @ file:///C:/b/abs_73u73l7pl9/croot/jsonpointer_1753788460913/work
jsonschema @ file:///C:/miniconda3/conda-bld/jsonschema_1762459308681/work
jsonschema-specifications @ file:///C:/miniconda3/conda-bld/jsonschema-specifications_1762788613133/work
jupyter @ file:///C:/Users/dev-admin/buildout/croot/jupyter_1742594998199/work
jupyter-console @ file:///C:/Users/dev-admin/buildout/croot/jupyter_console_1739561496258/work
jupyter-events @ file:///C:/b/abs_9cm3qlticu/croot/jupyter_events_1741184612840/work
jupyter-lsp @ file:///C:/b/abs_7171flzdkg/croot/jupyter-lsp-meta_1745827033118/work
jupyter_client @ file:///C:/miniconda3/conda-bld/jupyter_client_1762943100578/work
jupyter_core @ file:///C:/b/abs_7c6fipznw3/croot/jupyter_core_1751991383524/work
jupyter_server @ file:///C:/b/abs_cdpu8und98/croot/jupyter_server_1751996637146/work
jupyter_server_terminals @ file:///C:/b/abs_adjrm9dtns/croot/jupyter_server_terminals_1744706714294/work
jupyterlab @ file:///C:/miniconda3/conda-bld/jupyterlab_1758125082061/work
jupyterlab_pygments @ file:///C:/b/abs_d5alfet8m6/croot/jupyterlab_pygments_1741124274578/work
jupyterlab_server @ file:///C:/miniconda3/conda-bld/jupyterlab_server_1761751443648/work
jupyterlab_widgets @ file:///C:/b/abs_6566by8dag/croot/jupyterlab_widgets_1752066574111/work
keyring @ file:///C:/miniconda3/conda-bld/keyring_1763637203252/work
kiwisolver @ file:///C:/miniconda3/conda-bld/kiwisolver_1764159357446/work
lazy_loader @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/lazy_loader_1729054947204/work
lckr_jupyterlab_variableinspector @ file:///C:/b/abs_a7k1hndm37/croot/jupyterlab-variableinspector_1744638305846/work
libarchive-c @ file:///croot/python-libarchive-c_1726069797193/work
libmambapy @ file:///C:/miniconda3/conda-bld/mamba-split_1763111608356/work/libmambapy
lief @ file:///C:/miniconda3/conda-bld/lief_1762942044025/work/api/python
linkify-it-py @ file:///C:/miniconda3/conda-bld/linkify-it-py_1758717669406/work
llvmlite @ file:///C:/miniconda3/conda-bld/llvmlite_1760469323312/work
lmdb @ file:///C:/miniconda3/conda-bld/python-lmdb_1764243825905/work
locket @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/locket_1729042822914/work
lsprotocol @ file:///C:/miniconda3/conda-bld/lsprotocol_1759828550184/work/packages/python
lxml @ file:///C:/miniconda3/conda-bld/lxml_1764009763146/work
lz4 @ file:///C:/miniconda3/conda-bld/lz4_1762954228844/work
Markdown @ file:///C:/b/abs_f9hbi7znfr/croot/markdown_1746114643651/work
markdown-it-py @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/markdown-it-py_1729039967492/work
MarkupSafe @ file:///C:/b/abs_a0ma7ge0jc/croot/markupsafe_1738584052792/work
matplotlib==3.10.6
matplotlib-inline @ file:///C:/miniconda3/conda-bld/matplotlib-inline_1762779276169/work
mccabe @ file:///opt/conda/conda-bld/mccabe_1644221741721/work
mdit-py-plugins @ file:///C:/b/abs_88j0o6_jpr/croot/mdit-py-plugins_1756381038807/work
mdurl @ file:///C:/miniconda3/conda-bld/mdurl_1758552277768/work
menuinst @ file:///C:/miniconda3/conda-bld/menuinst_1762860868009/work
mistune @ file:///C:/b/abs_77yql3poyz/croot/mistune_1741124004410/work
mkl-service==2.5.2
mkl_fft @ file:///C:/miniconda3/conda-bld/mkl_fft_1761592916781/work
mkl_random @ file:///C:/miniconda3/conda-bld/mkl_random_1761593076691/work
more-itertools @ file:///C:/miniconda3/conda-bld/more-itertools_1761121564395/work
mpi4py @ file:///C:/b/abs_2c72fs0pz9/croot/mpi4py_1749458512296/work
mpmath @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/mpmath_1729048934933/work
msgpack @ file:///C:/b/abs_4b3t4uhz3r/croot/msgpack-python_1750958631084/work
multidict @ file:///C:/miniconda3/conda-bld/multidict_1760566895443/work
multipledispatch @ file:///C:/miniconda3/conda-bld/multipledispatch_1756978485717/work
mypy @ file:///C:/miniconda3/conda-bld/mypy-split_1761904873187/work
mypy_extensions @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/mypy_extensions_1729049023435/work
narwhals @ file:///C:/miniconda3/conda-bld/narwhals_1760003513313/work
navigator-updater @ file:///C:/miniconda3/conda-bld/navigator-updater_1761563279412/work
nbclient @ file:///C:/b/abs_a09c4t3h8x/croot/nbclient_1741124030330/work
nbconvert @ file:///C:/b/abs_c27_60dzt8/croot/nbconvert-meta_1741191385337/work
nbformat @ file:///C:/Users/dev-admin/buildout/croot/nbformat_1739559077024/work
nest_asyncio @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/nest-asyncio_1729042999160/work
networkx @ file:///C:/b/abs_6c02vx1ct4/croot/networkx_1756709289161/work
nltk @ file:///C:/miniconda3/conda-bld/nltk_1761121193106/work
notebook @ file:///C:/b/abs_ddnsjx06fh/croot/notebook_1756709315423/work
notebook_shim @ file:///C:/b/abs_9ctyfgpncn/croot/notebook-shim_1741707829491/work
numba @ file:///C:/miniconda3/conda-bld/numba_1760991948802/work
numexpr @ file:///C:/miniconda3/conda-bld/numexpr_1762165724132/work
numpy @ file:///C:/miniconda3/conda-bld/numpy_and_numpy_base_1763980694785/work/dist/numpy-2.3.5-cp313-cp313-win_amd64.whl#sha256=242110f8490d8f1e8ed7b1fb286cc718d5e96f1ba89bee9e7f807ccf5cbe59e6
numpydoc @ file:///C:/b/abs_e63bcy53_z/croot/numpydoc_1750958653347/work
openpyxl @ file:///C:/b/abs_6cdczthntz/croot/openpyxl_1736371239628/work
overrides @ file:///C:/miniconda3/conda-bld/overrides_1762349109990/work
packaging @ file:///C:/miniconda3/conda-bld/packaging_1761049099114/work
pandas @ file:///C:/miniconda3/conda-bld/pandas_1762332401545/work/dist/pandas-2.3.3-cp313-cp313-win_amd64.whl#sha256=9d93408ded21463dc4a0cce0d61428cd756d3f130f78ca53bfb6d1c81fedaa66
pandocfilters @ file:///C:/miniconda3/conda-bld/pandocfilters_1756977623249/work
panel @ file:///C:/miniconda3/conda-bld/panel_1762899230457/work
param @ file:///C:/miniconda3/conda-bld/param_1763638469890/work
parsel @ file:///C:/miniconda3/conda-bld/parsel_1761560684296/work
parso @ file:///C:/miniconda3/conda-bld/parso_1762781952168/work
partd @ file:///C:/b/abs_e1k4ow1dv4/croot/partd_1736803443606/work
pathspec @ file:///C:/miniconda3/conda-bld/pathspec_1761820745063/work
patsy @ file:///C:/b/abs_f9h0eiedk0/croot/patsy_1738159949276/work
pexpect @ file:///C:/miniconda3/conda-bld/pexpect_1762535956813/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
pillow @ file:///C:/miniconda3/conda-bld/pillow_1762528255883/work
pkce @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pkce_1729049216383/work
pkginfo @ file:///C:/b/abs_79p91g_cie/croot/pkginfo_1743184772345/work
platformdirs @ file:///C:/miniconda3/conda-bld/platformdirs_1762356623609/work
plotly @ file:///C:/b/abs_8926yyyylu/croot/plotly_1756453681452/work
pluggy @ file:///C:/b/abs_dfec_m79vo/croot/pluggy_1733170145382/work
prometheus_client @ file:///C:/b/abs_8b175q_ub8/croot/prometheus_client_1744271638821/work
prompt_toolkit @ file:///C:/miniconda3/conda-bld/prompt-toolkit_1761745018781/work
propcache @ file:///C:/b/abs_57780xb0gk/croot/propcache_1744012740137/work
Protego @ file:///C:/b/abs_48sti5uql_/croot/protego_1746479771804/work
protobuf @ file:///C:/b/abs_b5v84rwh56/croot/protobuf_1742419721750/work/bazel-bin/python/dist/protobuf-5.29.3-cp313-abi3-win_amd64.whl#sha256=0ef6aadfdcd9f988cbfc2d48eb8f7ed3d64acc158314c82a3a9c456f3fcc53a4
psutil @ file:///C:/miniconda3/conda-bld/psutil_1761896538278/work
ptyprocess @ file:///opt/miniconda3/conda-bld/ptyprocess_1762424170819/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl#sha256=3470be7f810474c8a2ecfcd6e02acc6aea8483ab595417fa4e336362a349933e
pure_eval @ file:///C:/miniconda3/conda-bld/pure_eval_1757067099531/work
py-cpuinfo @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/py-cpuinfo_1729051209925/work
pyarrow @ file:///C:/miniconda3/conda-bld/pyarrow_1759833600190/work/python
pyasn1 @ file:///C:/Users/dev-admin/buildout/perseverance-python-buildout/croot/pyasn1_1731744867547/work
pyasn1_modules @ file:///C:/b/abs_12mhyss7ds/croot/pyasn1-modules_1752042911584/work
pycares @ file:///C:/b/abs_b36fcwt8zj/croot/pycares_1756217945340/work
pycodestyle @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pycodestyle_1729051264017/work
pycosat @ file:///C:/b/abs_18nblzzn70/croot/pycosat_1736868434419/work
pycparser @ file:///C:/miniconda3/conda-bld/pycparser_1757496153123/work
pyct @ file:///C:/miniconda3/conda-bld/pyct_1759932166264/work
pycurl @ file:///C:/miniconda3/conda-bld/pycurl_1761132136915/work
pydantic @ file:///C:/miniconda3/conda-bld/pydantic_1764083582233/work
pydantic-settings @ file:///C:/miniconda3/conda-bld/pydantic-settings_1764165236385/work
pydantic_core @ file:///C:/miniconda3/conda-bld/pydantic-core_1764009799098/work
PyDispatcher @ file:///C:/b/abs_7bay5wbi80/croot/pydispatcher_1750159265590/work
pydocstyle @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pydocstyle_1729055775306/work
pyerfa @ file:///C:/b/abs_35x4fn08_4/croot/pyerfa_1738083087918/work
pyflakes @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pyflakes_1729051360949/work
PyGithub @ file:///C:/miniconda3/conda-bld/pygithub_1762271604729/work
Pygments @ file:///C:/miniconda3/conda-bld/pygments_1762431428918/work
PyJWT @ file:///C:/Users/dev-admin/buildout/croot/pyjwt_1739559988030/work
pylint @ file:///C:/b/abs_6dheb4r34g/croot/pylint_1756473040471/work
pylint-venv @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pylint-venv_1729062196487/work
pyls-spyder==0.4.0

In [16]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [3]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|', index_col='user_id')
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries
Solve it by 2 different ways

In [5]:
users[:25]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [6]:
users.loc[:25, :]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [17]:
print(users.iloc[3, 2])

users.loc[10, "age"]

technician

np.int64(53)

### Step 5. See the last 10 entries

In [6]:
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [7]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [9]:
users.loc[len(users)-10:, :]

         age gender     occupation zip_code
user_id
933       28      M        student    48105
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [10]:
users.iloc[-10::, : ]

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [11]:
users.iloc[:-10]

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213
...      ...    ...         ...      ...
929       44      M   scientist    53711
930       28      F   scientist    07310
931       60      M    educator    33556
932       58      M    educator    06437
933       28      M     student    48105

[933 rows x 4 columns]

### Step 6. What is the number of observations in the dataset?
Solve it by 2 different ways

In [18]:
len(users)

943

In [13]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 76.8+ KB

In [14]:
users.keys()

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [15]:
list(users.items())

[('age',
  user_id
  1      24
  2      53
  3      23
  4      24
  5      33
         ..
  939    26
  940    32
  941    20
  942    48
  943    22
  Name: age, Length: 943, dtype: int64),
 ('gender',
  user_id
  1      M
  2      F
  3      M
  4      M
  5      F
        ..
  939    F
  940    M
  941    M
  942    F
  943    M
  Name: gender, Length: 943, dtype: object),
 ('occupation',
  user_id
  1         technician
  2              other
  3             writer
  4         technician
  5              other
             ...
  939          student
  940    administrator
  941          student
  942        librarian
  943          student
  Name: occupation, Length: 943, dtype: object),
 ('zip_code',
  user_id
  1      85711
  2      94043
  3      32067
  4      43537
  5      15213
         ...
  939    33319
  940    02215
  941    97229
  942    78209
  943    77841
  Name: zip_code, Length: 943, dtype: object)]

In [16]:
users['age'].size

943

In [17]:
users.shape

(943, 4)

In [18]:
users.size

3772

### Step 7. What is the number of columns in the dataset?
Solve it by 2 different ways

In [19]:
len(users.columns)

4

### Step 8. Print the name of all the columns.

In [20]:
users.columns.values

array(['age', 'gender', 'occupation', 'zip_code'], dtype=object)

In [21]:
users.keys()

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed? Get the index values

In [22]:
users.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?
Solve it by 2 different ways

In [23]:
users.info

<bound method DataFrame.info of          age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]>

In [24]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column
Solve it by 2 different ways

In [25]:
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [26]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset? How many users per occupation are in the dataset?

In [27]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [28]:
users['occupation'].value_counts()

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: occupation, dtype: int64

In [29]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [30]:
users['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [31]:
ocupaciones = users.groupby ('occupation').size()
print(ocupaciones)

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
dtype: int64

### Step 14. Summarize the DataFrame.

In [34]:
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [35]:
users.sum()

age                                                       32111
gender        MFMMFMMMMMFFMMFMMFMFMMFFMMFMMMMFMFFFMFMMMMFMMF...
occupation    technicianotherwritertechnicianotherexecutivea...
zip_code      8571194043320674353715213981019134405201010029...
dtype: object

In [36]:
users.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [38]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [39]:
print(users.groupby(by=['occupation']).sum())

                age
occupation
administrator  3061
artist          879
doctor          305
educator       3991
engineer       2438
entertainment   526
executive      1239
healthcare      665
homemaker       228
lawyer          441
librarian      2040
marketing       978
none            239
other          3625
programmer     2186
retired         883
salesman        428
scientist      1102
student        4328
technician      895
writer         1634

In [41]:
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 17. What is the mean age of users?

In [42]:
users['age'].mean()

34.05196182396607

In [43]:
media_age = users['age'].mean()
print(media_age)

34.05196182396607